export const HEADER_CSS_VARIABLES = {
  colorBrand: "--header-color-brand",
  colorAccent: "--header-color-accent",
  colorSurface: "--header-color-surface",
  colorSurfaceCollapsed: "--header-color-surface-collapsed",
  colorSurfaceCollapsedTranslucent:
    "--header-color-surface-collapsed-translucent",
  colorSurfaceElevated: "--header-color-surface-elevated",
  colorText: "--header-color-text",
  colorTextMuted: "--header-color-text-muted",
  colorTextInverse: "--header-color-text-inverse",
  colorTextOnLight: "--header-color-text-on-light",
  colorBorder: "--header-color-border",
  colorTopBarText: "--header-color-top-bar-text",
  colorNavUnderlineEnd: "--header-color-nav-underline-end",
  focusColor: "--header-focus-color",
  shadowCollapsed: "--header-shadow-collapsed",
  shadowMobileMenu: "--header-shadow-mobile-menu",
  shadowLogo: "--header-shadow-logo",
  zIndex: "--header-z-index",
  heightTopBar: "--header-height-top-bar",
  heightMainBar: "--header-height-main-bar",
  heightCollapsed: "--header-height-collapsed",
  contentMaxWidth: "--header-content-max-width",
  logoWidthExpanded: "--header-logo-width-expanded",
  logoWidthCollapsed: "--header-logo-width-collapsed",
  logoWidthMobile: "--header-logo-width-mobile",
  logoWidthMobileCollapsed: "--header-logo-width-mobile-collapsed",
  logoCollapsedScale: "--header-logo-collapsed-scale",
  brandCollapsedInlineStart: "--header-brand-collapsed-inline-start",
  navGap: "--header-nav-gap",
  navGapWide: "--header-nav-gap-wide",
  navInlineEnd: "--header-nav-inline-end",
  menuBarWidth: "--header-menu-bar-width",
  menuBarHeight: "--header-menu-bar-height",
  menuBarGap: "--header-menu-bar-gap",
  menuBarTransformOffset: "--header-menu-bar-transform-offset",
  mobileMenuOffset: "--header-mobile-menu-offset",
  transitionDurationSlow: "--header-transition-duration-slow",
  transitionDurationFast: "--header-transition-duration-fast",
  transitionEase: "--header-transition-ease",
} as const;

export type HeaderCssVariable =
  (typeof HEADER_CSS_VARIABLES)[keyof typeof HEADER_CSS_VARIABLES];
